website/views.py
from flask import Blueprint ,render_template , request ,redirect ,url_for
from flask_login import login_user , login_required , logout_user , current_user
from website.forms import hm , ElectricGuitarForm ,AcousticGuitarForm, BassGuitarForm ,OtherForm
from website.dbconnect import get_mysql_guitars
from website.functions import  Jsonify , generate_code
from mysql.connector import Error




views = Blueprint( 'views' , __name__ ) 



@views.route('/departments', methods=['GET','POST'])
@login_required
def departments():
    try:
       db = get_mysql_guitars() 
    except:
       return render_template("databasefail.html") 

    return render_template("departments.html")




@views.route('/electric' , methods=['GET','POST'])
@login_required
def electric():
    try:
       db = get_mysql_guitars() 
    except:
       return render_template("databasefail.html")
    
    basequery='SELECT * FROM product_catalog.electric_guitars;'
    db =get_mysql_guitars()
    cursor = db.cursor()
    cursor.execute(basequery)
    data = cursor.fetchall()
    
    
    if 'code' in request.form:
        
        code = request.form['code']
        if code.isspace() or code == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.electric_guitars where product_code='{code}'")
                 data = cursor.fetchall() 


    if 'brand' in request.form:
        
        brand = request.form['brand']
        if brand.isspace() or brand == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.electric_guitars where brand='{brand}'")
                 data = cursor.fetchall()              
               

    if 'model' in request.form:
        
        model = request.form['model']
        if model.isspace() or model == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.electric_guitars where model='{model}'")
                 data = cursor.fetchall() 


    if 'remove' in request.form:
        
        remove = request.form['remove']
        if remove.isspace() or remove == '':
                 cursor.execute(basequery)
                  
        else:
                try:
                 cursor.execute(f"DELETE FROM `product_catalog`.`electric_guitars` WHERE (`product_code` = '{remove}');")
                 data =  db.commit()
                 return render_template("electricdel.html")
                except: 
                     return  "Error"

                             
    
    return render_template("electric.html", data=data  )







@views.route('/acoustic', methods=['GET','POST'])
@login_required
def acoustic():
    try:
       db = get_mysql_guitars() 
    except:
       return render_template("databasefail.html")
     
    basequery='SELECT * FROM product_catalog.acoustic_guitars;'
    db =get_mysql_guitars()
    cursor = db.cursor()
    cursor.execute(basequery)
    data = cursor.fetchall()

    if 'code' in request.form:
        
        code = request.form['code']
        if code.isspace() or code == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.acoustic_guitars where product_code='{code}'")
                 data = cursor.fetchall() 


    if 'brand' in request.form:
        
        brand = request.form['brand']
        if brand.isspace() or brand == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.acoustic_guitars where brand='{brand}'")
                 data = cursor.fetchall()              
               

    if 'model' in request.form:
        
        model = request.form['model']
        if model.isspace() or model == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.acoustic_guitars where model='{model}'")
                 data = cursor.fetchall() 
    if 'remove' in request.form:
        
        remove = request.form['remove']
        if remove.isspace() or remove == '':
                 cursor.execute(basequery)
                  
        else:
                try:
                 cursor.execute(f"DELETE FROM `product_catalog`.`acoustic_guitars` WHERE (`product_code` = '{remove}');")
                 data =  db.commit()
                 return render_template("acousticdel.html")
                except: 
                     return  "Error"
    

    return render_template("acoustics.html",data=data)



@views.route('/classical', methods=['GET','POST'])
@login_required
def classical():


   try:
       db = get_mysql_guitars() 
   except:
       return render_template("databasefail.html")
    
   basequery='SELECT * FROM product_catalog.classical_guitars;'
   db =get_mysql_guitars()
   cursor = db.cursor()
   cursor.execute(basequery)
   data = cursor.fetchall()
   if 'code' in request.form:
        
        code = request.form['code']
        if code.isspace() or code == '':
                 
                 cursor.execute()
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.classical_guitars where product_code='{code}'")
                 data = cursor.fetchall() 

   if 'brand' in request.form:
        
        brand = request.form['brand']
        if brand.isspace() or brand == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.classical_guitars where brand='{brand}'")
                 data = cursor.fetchall()              
               

   if 'model' in request.form:
        
        model = request.form['model']
        if model.isspace() or model == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.classical_guitars where model='{model}'")
                 data = cursor.fetchall() 
   if 'remove' in request.form:
        
        remove = request.form['remove']
        if remove.isspace() or remove == '':
                 cursor.execute(basequery)
                  
        else:
                try:
                 cursor.execute(f"DELETE FROM `product_catalog`.`classical_guitars` WHERE (`product_code` = '{remove}');")
                 data =  db.commit()
                 return render_template("classicaldel.html")
                except: 
                     return  "Error"

    
   return render_template("classical.html",data=data)




@views.route('/bass' , methods=['GET','POST'])
@login_required
def bass():

   try:
       db = get_mysql_guitars() 
   except:
       return render_template("databasefail.html")
   

   basequery='SELECT * FROM product_catalog.bass_guitars;'
   db =get_mysql_guitars()
   cursor = db.cursor()
   cursor.execute(basequery)
   data = cursor.fetchall()

   if 'code' in request.form:
        
       code = request.form['code']
       if code.isspace() or code == '':
                 
             cursor.execute(basequery)
        
       else:
            cursor.execute(f"SELECT * FROM product_catalog.bass_guitars where product_code='{code}'")
            data = cursor.fetchall() 



   if 'brand' in request.form:
        
        brand = request.form['brand']
        if brand.isspace() or brand == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.bass_guitars where brand='{brand}'")
                 data = cursor.fetchall()              
               



   if 'model' in request.form:
        
        model = request.form['model']
        if model.isspace() or model == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.bass_guitars where model='{model}'")
                 data = cursor.fetchall() 
   if 'remove' in request.form:
        
        remove = request.form['remove']
        if remove.isspace() or remove == '':
                 cursor.execute(basequery)
                  
        else:
                try:
                 cursor.execute(f"DELETE FROM `product_catalog`.`bass_guitars` WHERE (`product_code` = '{remove}');")
                 data =  db.commit()
                 return render_template("bassdel.html")
                except: 
                     return  "Error"
 

   return render_template("bass.html",data=data)



@views.route('/other', methods=['GET', 'POST'])
@login_required
def other():

   try:
       db = get_mysql_guitars() 
   except:
       return render_template("databasefail.html")

   basequery='SELECT * FROM product_catalog.other;'
   db =get_mysql_guitars()
   cursor = db.cursor()
   cursor.execute(basequery)
   data = cursor.fetchall()


   if 'code' in request.form:
        
       code = request.form['code']
       if code.isspace() or code == '':
                 
             cursor.execute(basequery)
        
       else:
            cursor.execute(f"SELECT * FROM product_catalog.other where product_code='{code}'")
            data = cursor.fetchall() 



   if 'brand' in request.form:
        
        brand = request.form['brand']
        if brand.isspace() or brand == '':
                 
                 cursor.execute(basequery)
        
        else:
                 cursor.execute(f"SELECT * FROM product_catalog.other where brand='{brand}'")
                 data = cursor.fetchall()              
               



   if 'prod' in request.form:
        
        prod = request.form['prod']
        if prod.isspace() or prod == '':
                 

website/templates/acousticdel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
      <H1>Removed Successfully</H1>

    <button class="button" onclick="window.location.href = '/acoustic';">Acoustic Guitars</button>
</body>
</html>

website/templates/acoustics.html
<!DOCTYPE html>
<html>
<head>
    <title>Electric Guitars</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #2c9d6a;
        }

        tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>
<body>
    <h1>Acoustic Guitars</h1>
    <div style="display: flex; justify-content: flex-start ; justify-content: space-around;">


        <form method="POST" action="{{ url_for('views.acoustic') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Product Code: <input type="text" name="code">
            <input type="submit" value="Search">
        </form>


        <form method="POST" action="{{ url_for('views.acoustic') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Brand: <input type="text" name="brand">
            <input type="submit" value="Search">
        </form>

          <form method="POST" action="{{ url_for('views.acoustic') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Model: <input type="text" name="model">
            <input type="submit" value="Search">
        </form>

        <form method="POST" action="{{ url_for('views.acoustic') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Remove By Product Code: <input type="text" name="remove">
            <input type="submit" value="Remove">
        </form> 


        <button class="button" onclick="window.location.href = '/add_acoustic';">Add Guitar</button>
        <button class="button" onclick="window.location.href = '/departments';">Departments Page</button>

   </div>
    <table>
        <thead>
            <tr>
                <th>Product Code</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Neck Shape</th>
                <th>Woods</th>
                <th>Number of Frets</th>
                <th>Number of Strings</th>
                <th>Number of Pickups</th>
                <th>Pickup Type</th>
                <th>Price</th>
               
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                <td>{{ row[0] }}</td>
                <td>{{ row[1] }}</td>
                <td>{{ row[2] }}</td>
                <td>{{ row[3] }}</td>
                <td>
                    {% set json_string = row[4]  | replace('{', '') | replace('}', '') | replace('"', '') | replace(',', ' | ') %}
                    {{ json_string }}
                </td>
                <td>{{ row[5] }}</td>
                <td>{{ row[6] }}</td>
                <td>{{ row[7] }}</td>
                <td>{{ row[8] }}</td>
                <td>{{ row[9] }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

website/templates/addacoustic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Guitar</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }
        
        .form {
            max-width: 400px;
            margin: 20px auto;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        .form input[type="text"] {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        .form input[type="number"],
        .form select {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        
        
        .form input[type="submit"] {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: #ffffff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
        .form input[type="submit"]:hover {
            background-color: #45a049;
        }
        
    </style>
</head>
<body>
    <form class="form" action="" method="POST">
        {{ form.csrf_token }}
        <label for="brand">Brand:</label>
        <input type="text" id="brand" name="brand" required aria-required="true">
        
        <label for="model">Model:</label>
        <input type="text" id="model" name="model" required aria-required="true">
        
        <label for="neck-shape">Neck Shape:</label>
        <select id="shape" name="shape" required>
            <option value="C">C Shape</option>
            <option value="D">D Shape</option>
            <option value="U">U Shape</option>
            <option value="V">V Shape</option>
        </select>
        
        <label for="top-wood">Top Wood:</label>
        <input type="text" id="top-wood" name="top" required aria-required="true">
        
        <label for="body-wood">Body Wood:</label>
        <input type="text" id="body-wood" name="body" required aria-required="true">
        
        <label for="neck">Neck Material:</label>
        <input type="text" id="neck" name="neck" required aria-required="true">

        <label for="neck">Fretboard Material:</label>
        <input type="text" id="fretboard" name="fretboard" required aria-required="true">
        
        <label for="frets">Number of Frets:</label>
        <input type="number" id="frets" name="frets" required aria-required="true" min="15", max="30">
        
        <label for="strings">Number of Strings:</label>
        <input type="number" id="strings" name="strings" required aria-required="true" min="6", max="18" >
        
        <label for="pickupnum">Number Of Pickups:</label>
        <input type="number" id="pickupnum" name="pickupnum" required aria-required="true">

        <label for="pickuptype">Pickup Type:</label>
        <select id="pickuptype" name="pickuptype" required>
            <option value="Piezo">None</option>
            <option value="Single Coil">Single Coil</option>
            <option value="P90">P90</option>
            <option value="Humbucker">Piezo</option>
        </select>
        <br>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" required aria-required="true" min="0" min="0" max="30000">
        
        <input type="submit" value="Add Guitar">
    </form>
</body>
</html>

website/templates/addbass.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Guitar</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
        }
        
        .form {
            max-width: 400px;
            margin: 20px auto;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        .form input[type="text"] {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        .form input[type="number"],
        .form select {
            display: block;
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        
        
        .form input[type="submit"] {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: #ffffff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        
        .form input[type="submit"]:hover {
            background-color: #45a049;
        }
        
    </style>
</head>
<body>

    
    <form class="form" action="" method="POST">
        {{ form.csrf_token }}
        <label for="brand">Brand:</label>
        <input type="text" id="brand" name="brand" required aria-required="true">
        
        <label for="model">Model:</label>
        <input type="text" id="model" name="model" required aria-required="true">


        <label for="type">Type:</label>
        <select id="type" name="type" required>
            <option value="Electric">Electric</option>
            <option value="Acoustic">Acoustic</option>
        </select>


        <label for="neck-shape">Neck Shape:</label>
        <select id="shape" name="shape" required>
            <option value="C">C Shape</option>
            <option value="D">D Shape</option>
            <option value="U">U Shape</option>
            <option value="V">V Shape</option>
        </select>
        
        <label for="top-wood">Top Wood:</label>
        <input type="text" id="top-wood" name="top" required aria-required="true">
        
        <label for="body-wood">Body Wood:</label>
        <input type="text" id="body-wood" name="body" required aria-required="true">
        
        <label for="neck">Neck Material:</label>
        <input type="text" id="neck" name="neck" required aria-required="true">

        <label for="neck">Fretboard Material:</label>
        <input type="text" id="fretboard" name="fretboard" required aria-required="true">
        
        <label for="frets">Number of Frets:</label>
        <input type="number" id="frets" name="frets" required aria-required="true" min="15", max="30">
        
        <label for="strings">Number of Strings:</label>
        <input type="number" id="strings" name="strings" required aria-required="true"  min="5", max="8" >

        <label for="pickupnum">Number Of Pickups:</label>
        <input type="number" id="pickupnum" name="pickupnum" required aria-required="true" min="0", max="3">

        <label for="pickuptype">Pickup Type:</label>
        <select id="pickuptype" name="pickuptype" required>
            <option value="Humbucker">Humbucker</option>
            <option value="Single Coil">Single Coil</option>
            <option value="P90">P90</option>
        </select>
        <br>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price" required aria-required="true" min="0">
        
        <input type="submit" value="Add Guitar">
    </form>
</body>
</html>

website/templates/bass.html
<!DOCTYPE html>
<html>
<head>
    <title>Bass Guitars</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #2c9d6a;
        }

        tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>
<body>
    <h1>Bass Guitars</h1>
    <div style="display: flex; justify-content: flex-start ; justify-content: space-around;">


        <form method="POST" action="{{ url_for('views.bass') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Product Code: <input type="text" name="code">
            <input type="submit" value="Search">
        </form>


        <form method="POST" action="{{ url_for('views.bass') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Brand: <input type="text" name="brand">
            <input type="submit" value="Search">
        </form>

          <form method="POST" action="{{ url_for('views.bass') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Model: <input type="text" name="model">
            <input type="submit" value="Search">
        </form>
        <form method="POST" action="{{ url_for('views.bass') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Remove By Product Code: <input type="text" name="remove">
            <input type="submit" value="Remove">
        </form>

        <button class="button" onclick="window.location.href = '/add_bass';">Add Guitar</button>
        <button class="button" onclick="window.location.href = '/departments';">Departments Page</button>

   </div>
    <table>
        <thead>
            <tr>
                <th>Product Code</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Type</th>
                <th>Neck Shape</th>
                <th>Woods</th>
                <th>Number Of Frets</th>
                <th>Number Of strings</th>
                <th>Pickup Number</th>
                <th>Pickup Type</th>
                <th>Price</th>
                
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                <td>{{ row[0] }}</td>
                <td>{{ row[1] }}</td>
                <td>{{ row[2] }}</td>
                <td>{{ row[3] }}</td>
                <td>{{ row[4] }}</td>
                <td>
                    {% set json_string = row[5]  | replace('{', '') | replace('}', '') | replace('"', '') | replace(',', ' | ') %}
                    {{ json_string }}
                </td>
                <td>{{ row[6] }}</td>
                <td>{{ row[7] }}</td>
                <td>{{ row[8] }}</td>
                <td>{{ row[9] }}</td>
                <td>{{ row[10] }}</td>
               
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

website/templates/classical.html
<!DOCTYPE html>
<html>
<head>
    <title>Electric Guitars</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #2c9d6a;
        }

        tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>
<body>
    <h1>Acoustic Guitars</h1>
    <div style="display: flex; justify-content: flex-start ; justify-content: space-around;">


        <form method="POST" action="{{ url_for('views.classical') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Product Code: <input type="text" name="code">
            <input type="submit" value="Search">
        </form>


        <form method="POST" action="{{ url_for('views.classical') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Brand: <input type="text" name="brand">
            <input type="submit" value="Search">
        </form>

          <form method="POST" action="{{ url_for('views.classical') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Model: <input type="text" name="model">
            <input type="submit" value="Search">
        </form>

        <form method="POST" action="{{ url_for('views.classical') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Remove By Product Code: <input type="text" name="remove">
            <input type="submit" value="Search">
        </form>

        <button class="button" onclick="window.location.href = '/add_classical';">Add Guitar</button>
        <button class="button" onclick="window.location.href = '/departments';">Departments Page</button>

   </form>

   </div>
    <table>
        <thead>
            <tr>
                <th>Product Code</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Neck Shape</th>
                <th>Woods</th>
                <th>Number of Frets</th>
                <th>Number of Strings</th>
                <th>Number of Pickups</th>
                <th>Pickup Type</th>
                <th>Price</th>
                
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                <td>{{ row[0] }}</td>
                <td>{{ row[1] }}</td>
                <td>{{ row[2] }}</td>
                <td>{{ row[3] }}</td>
                <td>
                    {% set json_string = row[4]  | replace('{', '') | replace('}', '') | replace('"', '') | replace(',', ' | ') %}
                    {{ json_string }}
                </td>
                <td>{{ row[5] }}</td>
                <td>{{ row[6] }}</td>
                <td>{{ row[7] }}</td>
                <td>{{ row[8] }}</td>
                <td>{{ row[9] }}</td>
               
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

website/templates/electric.html
<!DOCTYPE html>
<html>
<head>
    <title>Electric Guitars</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #2c9d6a;
        }

        tr:hover {
            background-color: #f5f5f5;
        }
    </style>
</head>
<body>
    <h1>Electric Guitars</h1>
    <div style="display: flex; justify-content: flex-start ; justify-content: space-around;">


        <form method="POST" action="{{ url_for('views.electric') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Product Code: <input type="text" name="code">
            <input type="submit" value="Search">
        </form>


        <form method="POST" action="{{ url_for('views.electric') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Brand: <input type="text" name="brand">
            <input type="submit" value="Search">
        </form>

          <form method="POST" action="{{ url_for('views.electric') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Search By Model: <input type="text" name="model">
            <input type="submit" value="Search">
        </form>

        <form method="POST" action="{{ url_for('views.electric') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            Remove By Product Code: <input type="text" name="remove">
            <input type="submit" value="Remove">
        </form>


        <button class="button" onclick="window.location.href = '/add_electric';">Add Guitar</button>
        <button class="button" onclick="window.location.href = '/departments';">Departments Page</button>
   </form>

   </div>
    <table>
        <thead>
            <tr>
                <th>Product Code</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Neck Shape</th>
                <th>Woods</th>
                <th>Number of Frets</th>
                <th>Number of Strings</th>
                <th>Number of Pickups</th>
                <th>Pickup Type</th>
                <th>Bridge Type</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                <td>{{ row[0] }}</td>
                <td>{{ row[1] }}</td>
                <td>{{ row[2] }}</td>
                <td>{{ row[3] }}</td>
                <td>
                    {% set json_string = row[4]  | replace('{', '') | replace('}', '') | replace('"', '') | replace(',', ' | ') %}
                    {{ json_string }}
                </td>
                <td>{{ row[5] }}</td>
                <td>{{ row[6] }}</td>
                <td>{{ row[7] }}</td>
                <td>{{ row[8] }}</td>
                <td>{{ row[9] }}</td>
                <td>{{ row[10] }}</td>
                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>